/** Diagram languages Kroki can render — use as markdown fence aliases. */
export const KROKI_DIAGRAM_ALIASES = [
  "actdiag",
  "blockdiag",
  "bpmn",
  "bytefield",
  "c4plantuml",
  "d2",
  "dbml",
  "diagramsnet",
  "ditaa",
  "erd",
  "excalidraw",
  "goat",
  "graphviz",
  "mermaid",
  "nomnoml",
  "nwdiag",
  "packetdiag",
  "pikchr",
  "plantuml",
  "rackdiag",
  "seqdiag",
  "structurizr",
  "svgbob",
  "symbolator",
  "tikz",
  "umlet",
  "vega",
  "vegalite",
  "wavedrom",
  "wireviz",
  // Common short aliases Kroki also accepts
  "dot",
  "c4",
];
